# Generated by Django 4.2.5 on 2023-10-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_userdetails_alter_temporary_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='id_proof',
            field=models.ImageField(null=True, upload_to='product-img/'),
        ),
    ]
