# Generated by Django 4.2.5 on 2023-10-02 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=60)),
                ('mileage', models.IntegerField()),
                ('ppd', models.IntegerField()),
                ('min_rent', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('status', models.CharField(default=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CarCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CarCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateField(default=datetime.datetime.utcnow)),
                ('rent_from', models.DateField()),
                ('rent_till', models.DateField()),
                ('car_taken', models.BooleanField(default=False)),
                ('car_delivery', models.BooleanField(default=False)),
                ('final_status', models.CharField(default=True, max_length=60)),
                ('said_date', models.BooleanField(default=True)),
                ('said_time', models.BooleanField(default=True)),
                ('proper_condition', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=200)),
                ('fine', models.IntegerField(default=0)),
                ('fine_paid', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('city_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_delivery', to='main.city')),
                ('city_taken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_taken', to='main.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('description', models.CharField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcategories'),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcompany'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodels'),
        ),
    ]
