# Generated by Django 4.2.5 on 2023-10-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_rented_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_id',
        ),
    ]
